//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré...
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptimizeBot.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OptimizeBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour vers {0}.
        /// </summary>
        internal static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir le &lt;b&gt;&lt;u&gt;montant&lt;/u&gt;&lt;/b&gt; pour lequel vous souhaitez faire un dépôt:.
        /// </summary>
        internal static string ServiceCashInOutEnterAmount {
            get {
                return ResourceManager.GetString("ServiceCashInOutEnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir &lt;b&gt;&lt;u&gt;l&apos;identifiant de la transaction&lt;/u&gt;&lt;/b&gt; telle qu&apos;il apparaît dans le message reçu de  &lt;b&gt;&lt;u&gt;{0}&lt;/u&gt;&lt;/b&gt;:.
        /// </summary>
        internal static string ServiceReceiptEnterTransactionId {
            get {
                return ResourceManager.GetString("ServiceReceiptEnterTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}_{1}_{2}.
        /// </summary>
        internal static string ServiceReceiptFileCaption {
            get {
                return ResourceManager.GetString("ServiceReceiptFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez patienter pendant que nous cherchons des informations sur votre reçu....
        /// </summary>
        internal static string ServiceReceiptPleaseWait {
            get {
                return ResourceManager.GetString("ServiceReceiptPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;b&gt;{0}&lt;/b&gt;{1}{1}Nous avons {2} fournisseurs proposant ce service. Veuillez en sélectionner un, au choix..
        /// </summary>
        internal static string ServiceSelectProvider {
            get {
                return ResourceManager.GetString("ServiceSelectProvider", resourceCulture);
            }
        }

        internal static string ServiceSingleProvider
        {
            get
            {
                return ResourceManager.GetString("ServiceSingleProvider", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;b&gt;{0}&lt;/b&gt;{1}{1}Bienvenue, {2}. Veuillez sélectionner un service au choix pour commencer..
        /// </summary>
        internal static string WelcomeUserSelectService {
            get {
                return ResourceManager.GetString("WelcomeUserSelectService", resourceCulture);
            }
        }

        internal static string WarningInvalidAmountFormat
        {
            get
            {
                return ResourceManager.GetString("WarningInvalidAmountFormat", resourceCulture);
            }
        }
        
        internal static string WarningAmountOverflow
        {
            get
            {
                return ResourceManager.GetString("WarningAmountOverflow", resourceCulture);
            }
        }
        
        internal static string ServiceCashInOutResult
        {
            get
            {
                return ResourceManager.GetString("ServiceCashInOutResult", resourceCulture);
            }
        }
        internal static string Retry
        {
            get
            {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        internal static string RetryAmount
        {
            get
            {
                return ResourceManager.GetString("RetryAmount", resourceCulture);
            }
        }
        
        internal static string RetryProvider
        {
            get
            {
                return ResourceManager.GetString("RetryProvider", resourceCulture);
            }
        } 
        
        internal static string Home
        {
            get
            {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string ServiceCashOut
        {
            get
            {
                return ResourceManager.GetString("ServiceCashOut", resourceCulture);
            }
        }
        
        internal static string ServiceCashIn
        {
            get
            {
                return ResourceManager.GetString("ServiceCashIn", resourceCulture);
            }
        }
        
        internal static string Yes
        {
            get
            {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No
        {
            get
            {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        internal static string WarningInvalidTrxId
        {
            get
            {
                return ResourceManager.GetString("WarningInvalidTrxId", resourceCulture);
            }
        }
        
        internal static string ErrorNotDownloaded
        {
            get
            {
                return ResourceManager.GetString("ErrorNotDownloaded", resourceCulture);
            }
        }
        
        internal static string About
        {
            get
            {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }


    }
}
